### ISSUE TITLE
Use preceding zero for single digit master/worker host names

### ISSUE THREAD

**Issue by acalhounRH** [bengland2/ocp4_upi_baremetal#3]
When analyzing data on Grafana, search/filter functions use regex strings to queries results, when filtering on a host, for example worker-1, the regex will match all host names with worker-1 that would include worker-11, 12, 13 and so on. If the worker is preceded with a zero it eliminates the issue. 

worker-01
worker-02
...
worker-09

Request would be that the automation scripts would be updated to adopt this convention.

**Comment by bengland2** [comment]
@acalhounRH agreed.    If we're ever good enough to get to > 99 workers will have to revisit ;-)  will try to get to that this week.  Or if you have a patch submit a PR!

**Comment by bengland2** [comment]
commit in discovery_enhance branch fixes this problem.   We can easily go to 3-digit workers if necessary.

**Comment by bengland2** [comment]
this did not succeed, it did not convince openshift to call them worker-NN, just the inventory file does it.    This is bad because the playbook can't talk to the workers.

```
[root@e24-h17-740xd ~]# oc get nodes
NAME       STATUS   ROLES    AGE     VERSION
master-0   Ready    master   34m     v1.17.1
master-1   Ready    master   34m     v1.17.1
master-2   Ready    master   33m     v1.17.1
worker-2   Ready    worker   2m55s   v1.17.1
worker-3   Ready    worker   3m49s   v1.17.1
```

**Comment by bengland2** [comment]
@acalhounRH  however, if we fix ocp4-upi-dnsmasq.conf.j2 to also do the same trick "{{ "%02d" | format(loop.index0) }}" instead of "{{ loop.index0 }}"  then I think it should work, hope to test it sometime this week.   Also, I don't think workers need etcd- entry so will try removing that.

**Comment by bengland2** [comment]
see post_install_fixes branch

**Comment by bengland2** [comment]
fixed
