### ISSUE TITLE
Failing to untar client and installer

### ISSUE THREAD

**Issue by acalhounRH** [bengland2/ocp4_upi_baremetal#5]
the task unzip each tarball so it is in PATH is failing with the folloing command, 

tar zxvf ~/openshift/openshift-client-linux*tar.gz
tar zxvf ~/openshift/openshift-install-linux*tar.gz

it fails because the download site has a version specific and non version specific tar files. 

suggest the following to match only the version specific copies 

tar zxvf ~/openshift/openshift-client-linux-*tar.gz
tar zxvf ~/openshift/openshift-install-linux-*tar.gz

**Comment by acalhounRH** [comment]
When Openshift is downloaded there are four files 

-rw-r--r--. 1 root root 27500714 Mar 10 13:12 openshift-client-linux.tar.gz
-rw-r--r--. 1 root root 27500714 Mar 10 13:12 openshift-client-linux-4.3.0-0.nightly-2020-03-10-182422.tar.gz
-rw-r--r--. 1 root root 82433903 Mar 10 17:38 openshift-install-linux.tar.gz
-rw-r--r--. 1 root root 82433903 Mar 10 17:38 openshift-install-linux-4.3.0-0.nightly-2020-03-10-182422.tar.gz

the wildcard * matches both and tar fails if you add a dash(-) after linux it will only resolve to the version specific tar file.

**Comment by bengland2** [comment]
clarification from Alex:

When Openshift is downloaded there are four files

-rw-r--r--. 1 root root 27500714 Mar 10 13:12 openshift-client-linux.tar.gz
-rw-r--r--. 1 root root 27500714 Mar 10 13:12 openshift-client-linux-4.3.0-0.nightly-2020-03-10-182422.tar.gz
-rw-r--r--. 1 root root 82433903 Mar 10 17:38 openshift-install-linux.tar.gz
-rw-r--r--. 1 root root 82433903 Mar 10 17:38 openshift-install-linux-4.3.0-0.nightly-2020-03-10-182422.tar.gz

the wildcard * matches both and tar fails if you add a dash(-) after linux it will only resolve to the version specific tar file.

**Comment by bengland2** [comment]
testing a fix to that today
